import { BlogPost } from './blog-post-page/blog-post';

export const blogPosts: BlogPost[] = [
  {
    title: 'Work-Life Balance Management for Optimum Performance',
    author: 'Nimer Shadida Johansson',
    category: 'lifestyle',
    publishedAt: new Date(2023, 4, 27),
    contentUrl: '',
    thumbnailImageUrl: '',
    headerImageUrl: '',
    slug: 'sample-post-1',
  },
  {
    title: 'Diam quam nulla porttitor massa id neque aliquam',
    author: 'Nimer Shadida Johansson',
    category: 'lifestyle',
    publishedAt: new Date(2023, 4, 27),
    contentUrl: '',
    thumbnailImageUrl: '',
    headerImageUrl: '',
    slug: 'sample-post-2',
  },
  {
    title:
      'Nam aliquam sem et tortor consequat id porta nibh venenatis cras sed',
    author: 'Nimer Shadida Johansson',
    category: 'update',
    publishedAt: new Date(2023, 4, 27),
    contentUrl: '',
    thumbnailImageUrl: '',
    headerImageUrl: '',
    slug: 'sample-post-3',
  },
  {
    title: 'Diam quam nulla porttitor massa id neque aliquam',
    author: 'Nimer Shadida Johansson',
    category: 'training',
    publishedAt: new Date(2023, 4, 27),
    contentUrl: '',
    thumbnailImageUrl: '',
    headerImageUrl: '',
    slug: 'sample-post-4',
  },
  {
    title: 'Diam quam nulla porttitor massa id neque aliquam',
    author: 'Nimer Shadida Johansson',
    category: 'lifestyle',
    publishedAt: new Date(2023, 4, 27),
    contentUrl: '',
    thumbnailImageUrl: '',
    headerImageUrl: '',
    slug: 'sample-post-5',
  },
  {
    title: 'Work-Life Balance Management for Optimum Performance',
    author: 'Nimer Shadida Johansson',
    category: 'lifestyle',
    publishedAt: new Date(2023, 4, 27),
    contentUrl: '',
    thumbnailImageUrl: '',
    headerImageUrl: '',
    slug: 'sample-post-1',
  },
  {
    title: 'Diam quam nulla porttitor massa id neque aliquam',
    author: 'Nimer Shadida Johansson',
    category: 'lifestyle',
    publishedAt: new Date(2023, 4, 27),
    contentUrl: '',
    thumbnailImageUrl: '',
    headerImageUrl: '',
    slug: 'sample-post-2',
  },
  {
    title:
      'Nam aliquam sem et tortor consequat id porta nibh venenatis cras sed',
    author: 'Nimer Shadida Johansson',
    category: 'update',
    publishedAt: new Date(2023, 4, 27),
    contentUrl: '',
    thumbnailImageUrl: '',
    headerImageUrl: '',
    slug: 'sample-post-3',
  },
  {
    title: 'Diam quam nulla porttitor massa id neque aliquam',
    author: 'Nimer Shadida Johansson',
    category: 'training',
    publishedAt: new Date(2023, 4, 27),
    contentUrl: '',
    thumbnailImageUrl: '',
    headerImageUrl: '',
    slug: 'sample-post-4',
  },
  {
    title: 'Diam quam nulla porttitor massa id neque aliquam',
    author: 'Nimer Shadida Johansson',
    category: 'lifestyle',
    publishedAt: new Date(2023, 4, 27),
    contentUrl: '',
    thumbnailImageUrl: '',
    headerImageUrl: '',
    slug: 'sample-post-5',
  },
].map(
  (blogPost) =>
    <BlogPost>{
      ...blogPost,
      contentUrl: `/assets/blog/${blogPost.slug}/content.md`,
      thumbnailImageUrl: `/assets/blog/${blogPost.slug}/image.jpg`,
      headerImageUrl: `/assets/blog/${blogPost.slug}/image.jpg`,
    }
);
