query fetchFreeShippingProduct($handle: String!, $countryCode: CountryCode!)
@inContext(country: $countryCode) {
  product(handle: $handle) {
    priceRange {
      minVariantPrice {
        amount
        currencyCode
      }
    }
  }
}
